# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Maithili Patel
description: >- # this means to ignore newlines until "baseurl:"
  Personal Page for Maithili Patel.
baseurl: "" # the subpath of the site
url: "https://maithili.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile.jpeg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    # - name: Research
    - name: News
    - name: Publications
    # - name: Blog
    - name: Hobbies

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: maithili at gatech dot edu
      # link: mailto:maithili@gatech.edu
  follow:
    - name: Google Scholar
      link: https://scholar.google.com/citations?user=dvqkwFYAAAAJ&hl=en
    - name: LinkedIn
      link: http://linkedin.com/in/Maithili
    - name: GitHub
      link: http://github.com/Maithili
    - name: Facebook
      link: https://www.facebook.com/Maithili3110

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1

collections:
  blogs:
    output: true
  projects:
    output: true
  research:
    output: true